Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Phelipe Santos
// Data atual  : 08/03/2023
Var
// Seção de Declarações das variáveis 
   nota: inteiro, nota2: real, nome: caractere, passou: logico;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo